### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jpretired** [UksusoFF/webtrees-faces#1]
I have installed the module.
After activating it no settings are available.
No errors in webtrees log.
I use webtrees 1.7.9

**Comment by UksusoFF** [comment]
Did you rename module folder follow [this instructions](https://github.com/UksusoFF/webtrees-photo_note_with_image_map#installation)?
Can you provide full path to module.php from your server?

**Comment by jpretired** [comment]
Of course I renamed it.
My webtrees is on localhost.
In module administration the module name links to
localhost/.../webtrees/admin_modules.php#

**Comment by UksusoFF** [comment]
> In module administration the module name links to
> localhost/.../webtrees/admin_modules.php#

No, I mean file path. Not url.
eg:
```/var/www/webtrees/modules_v3/photo_note_with_image_map/module.php```
or 
```C:\www\webtrees\modules_v3\photo_note_with_image_map\module.php```

**Comment by jpretired** [comment]
/var/www/Projekty/webtrees-1.7/modules_v3/photo_note_with_image_map/module.php

**Comment by UksusoFF** [comment]
Ok, this looks like normal. 
Any errors in apache/nginx logs?

**Comment by jpretired** [comment]
No errors in webtrees log, no errors in apache log.

**Comment by UksusoFF** [comment]
Wait. Can you show screenshot of your modules in webtrees admin (/admin_modules.php)?

And which theme you are used? Do you see (+) near photo in colorbox?

Any errors in browser console?

**Comment by jpretired** [comment]
Sorry, Kirill, I was wrong - the module works.
I did not know where to look for the plus sign. Now I can see it in colorbox near photo title. I also expected some settings to the module, there are probably none.
Thanks.

**Comment by UksusoFF** [comment]
Yep. Module settings still in todo list. 
Now it's show empty link because module implements ModuleConfigInterface for use database settings and must contain getConfigLink method.
Thank for feedback!
