### ISSUE TITLE
Support for more than one image/file in an media object

### ISSUE THREAD

**Issue by hartenthaler** [UksusoFF/webtrees-faces#11]
Webtrees supports since V2 more files/images in one media object. Your module is still working perfect, but the filename in the database field f_m_filename is not the filename of the used image with selected faces, it is the filename of the other file. The only effect is that in the admin screen of your module (which shows the list of all the images with selected faces), the wrong image is shown.

**Comment by miqrogroove** [comment]
There is another symptom: When sliding between different images for the same media object, the tags are displayed on all of the images, not just the tagged image.

**Comment by UksusoFF** [comment]
@miqrogroove can you describe steps how to add multiple files to one media?
Also any use cases will helpfull.

**Comment by hartenthaler** [comment]
My use case: I like to store the original scanned image in a media object and additionally a second version which is the result from editing the original with Photoshop, for example changing contrast, removing distortions, rotating, and cropping the image. Storing both in one media object helps to keep them together.
It is easy to add a second media file to an already existing media object: edit any media object which contains already an image file; in the last line you can find "add a media file". Then you have two media files in one object.

**Comment by miqrogroove** [comment]
My use case is to add the reverse side of a post card.  That image is secondary and less useful, but I like to keep the two sides together for easy reference.

**Comment by UksusoFF** [comment]
Seems at now I can only hide faces on images except first.
Because can't make up how connect data with other images - we have:
* fact id - but it's changed each time when edit media;
* images order - but it's also can be changed.

**Comment by UksusoFF** [comment]
Media filename not available on front end part :(

**Comment by miqrogroove** [comment]
Image order should be adequate.  If I go to an Album tab and click on the secondary image, the slideshow pops up the second image and allows me to rewind to the first.

**Comment by miqrogroove** [comment]
Also, if it's possible, the links should stay visible, and just remove the face rectangles.

**Comment by UksusoFF** [comment]
> Image order should be adequate.

Yep. But you can edit media via gedcom format and order can be changed.

**Comment by hartenthaler** [comment]
maybe Greg can help to find a solution

**Comment by UksusoFF** [comment]
Logic for work with multiple files added to master version. 
It's depend on media order so when you change it with GEDCOM editor you may got jumbled faces.
Please test it.

**Comment by UksusoFF** [comment]
Seems as fixed. Please reopen if any troubles with it.

**Comment by miqrogroove** [comment]
It's much better, and I have a question.  When I navigate between the images, both the tags and the sidebar links disappear.  I was thinking it would be relevant to keep the sidebar links, and only remove the face tags.  Would that make sense?  Or were you planning to have different people tagged on each image?

**Comment by UksusoFF** [comment]
> Or were you planning to have different people tagged on each image?

Each image now can have independent tags, so it's true.
