### ISSUE TITLE
+ button doesn't work

### ISSUE THREAD

**Issue by garraflavatra** [UksusoFF/webtrees-faces#12]
Hello,

I've installed the faces plugin. When I click on an image, the lightbox appears, but the `+` button doesn't work. My browser also throws an error on line 217 of the JS script:

```
undefined is not a function (near '...e.imgAreaSelect...')
```

Do you know what to do?

Thanks in advance.

**Comment by UksusoFF** [comment]
Seems you not fully copied javascript files.
Please describe how you install module? Also check webtrees/modules_v4/faces/build folder. It's contains vendor.min.js?

**Comment by garraflavatra** [comment]
I've tried to install the plugin again (downloaded and dropped source code into `modules_v4/faces`). The `webtrees/modules_v4/faces/build` folder doesn't exist. Do you mean the `webtrees/modules_v4/faces/resources/build`? That one does exist.

**Comment by UksusoFF** [comment]
Yep. This folder contains vendor.min.js? 

Which webtrees version you use? And which theme?

**Comment by garraflavatra** [comment]
Yes, that folder contains vendor.min.js.

I’m using webtrees 2.0.3 with the Minimal theme.

**Comment by UksusoFF** [comment]
Your webtrees instance is public? Can I see it?

**Comment by garraflavatra** [comment]
No, it isn’t public. But I can make you a video on how it’s going.

**Comment by UksusoFF** [comment]
Please check "Network" tab (near with "Console"). Any errors here?

**Comment by garraflavatra** [comment]
Yes:
```
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (vendor.min.js.map, line 0)
```

**Comment by garraflavatra** [comment]
And the other issue:
```
[Error] TypeError: undefined is not a function (near '...e.imgAreaSelect...')
	(anonieme functie) (index.php:1:5766)
	dispatch (vendor.min.js:2:239346)
```
That is displayed when I click the `+`button.

**Comment by UksusoFF** [comment]
.map file not required for proper module work.
At now I tested on webtrees 2.0.3 with url rewrite and without. In both variants all works. On minimal theme also. 
No idea whats wrong...

You use release webtrees version or master branch?

**Comment by UksusoFF** [comment]
Just insane guess.
Can you find `faces\resources\build\module.min.js` in network tab? 
Please compare header response with `faces\resources\build\vendor.min.js`

**Comment by garraflavatra** [comment]
Yes. These files are all included in the webpage.

**Comment by garraflavatra** [comment]
I think I've found the problem. You are bundling your JS files and dependencies with Webpack, right? Running Webpack may help.

I shall try it.

**Comment by garraflavatra** [comment]
That didn't work.

**Comment by UksusoFF** [comment]
> Yes. These files are all included in the webpage.

Please compare response headers for this files.
https://stackoverflow.com/questions/4423061/view-http-headers-in-google-chrome

**Comment by garraflavatra** [comment]
I've installed Faces again. It works.

I don't know what was wrong.

Thanks for your support!
