### ISSUE TITLE
Two Problems With Links

### ISSUE THREAD

**Issue by miqrogroove** [UksusoFF/webtrees-faces#14]
I have the "Create links" setting enabled and notice two significant problems.

If I click "Add a media object" on an individual page, the individual is already linked.  Then adding a face tag causes a 2nd link to be created.  I have to go back to the individual's Media tab to delete one of the links.

If I accidentally tag the wrong person and then delete the tag, the link to that wrong person is not deleted, and I have to go back to the individual's Media tab to delete the link.

**Comment by UksusoFF** [comment]
> If I click "Add a media object" on an individual page, the individual is already linked. Then adding a face tag causes a 2nd link to be created. I have to go back to the individual's Media tab to delete one of the links.

It's seems as bug. Will check it asap.

> If I accidentally tag the wrong person and then delete the tag, the link to that wrong person is not deleted, and I have to go back to the individual's Media tab to delete the link.

This is just not implemented yet. Not found easy way do it without dirty hacks.

**Comment by miqrogroove** [comment]
> This is just not implemented yet. Not found easy way do it without dirty hacks.

While it's not implemented, I think it would be important to have a message box that says "Face tag deleted.  Image still linked to this person."  Only needed if "Create links" is enabled.

Alternatively, you could also display all of the links and not just the tags.

**Comment by UksusoFF** [comment]
>> If I click "Add a media object" on an individual page, the individual is already linked. Then adding a face tag causes a 2nd link to be created. I have to go back to the individual's Media tab to delete one of the links.

> It's seems as bug. Will check it asap.

Tested it. Seems it's normal webtrees behavior. You also can do it on media page when adding new individual link many times.

**Comment by UksusoFF** [comment]
> While it's not implemented, I think it would be important to have a message box that says "Face tag deleted. Image still linked to this person." Only needed if "Create links" is enabled.

Added here: https://github.com/UksusoFF/webtrees-faces/commit/79d6cbaf95b817aa2faae67db2203df67ea26407

**Comment by UksusoFF** [comment]
> If I click "Add a media object" on an individual page, the individual is already linked. Then adding a face tag causes a 2nd link to be created. I have to go back to the individual's Media tab to delete one of the links.

Fixed here: https://github.com/UksusoFF/webtrees-faces/commit/e92d14415ebabf54f75e1716a1ffd6bd702c79ad
But works only if changed was accepted.

**Comment by UksusoFF** [comment]
Seems as fixed. Please reopen if any troubles with it.
