### ISSUE TITLE
Individual with No Name is Unlinked

### ISSUE THREAD

**Issue by miqrogroove** [UksusoFF/webtrees-faces#19]
I was just looking at a photo of an individual who is tagged, but who has no name record.  Instead of showing me "..." with a link, it shows me the record number and no link.  This is a bit strange.

**Comment by UksusoFF** [comment]
![image](https://user-images.githubusercontent.com/1931442/88630918-6716c600-d0c2-11ea-8264-bd2e5a653660.png)

How you attach them? I found it by their id (e.g. I7, X7) and now it's shown as "... ...".

**Comment by miqrogroove** [comment]
The individual was imported from GEDCOM, and has no NAME record at all.

The face tag was imported using face-tag-import.

**Comment by UksusoFF** [comment]
@miqrogroove please try [master](https://github.com/UksusoFF/webtrees-faces/archive/master.zip) version.

**Comment by miqrogroove** [comment]
I applied b31b3d3 to the DatabaseHelper and it works perfectly.
