### ISSUE TITLE
test 

### ISSUE THREAD

**Issue by Fa10175** [UksusoFF/webtrees-faces#2]
The module is loaded correctly
for the photos where we set name and area on 1.7, the zone and name are not displayed on last version.
for a new photo i don't saw how set a new zone and name.
in photo i saw just udefined(zoom) . if i click zoom zoom word  change to black to grey

on the face Maintenance i need more information for :
- missed notes find and delete.
- read xmp data
thanks

**Comment by UksusoFF** [comment]
@Fa10175 please try master version. Maybe fixed in https://github.com/UksusoFF/webtrees-faces/commit/8f862c4fe5ee32c4b6a43f9c6127e4122b82c092

**Comment by Fa10175** [comment]
i try it again after download again last master webtrees and your version after 8f862c4

I saw no change...

on database table module_setting i saw some line PNWIM_
and database table media_faces they are nothing

**Comment by UksusoFF** [comment]
@Fa10175 which module version you used before update?

**Comment by Fa10175** [comment]
for webtrees master `e35de89` 
yours 2.5 8f862c4

**Comment by UksusoFF** [comment]
@Fa10175 before update to webtrees 2.0?

**Comment by Fa10175** [comment]
i start my migration from webtrees 1.7.12 they are severall days ago to webtrees 2.0 and add last master
If you want i can try a new test may be tomorrow from database and webtrees 1.7.16

**Comment by UksusoFF** [comment]
@Fa10175 webtrees version does not matter. If you have backup please check which *module version* you have before update to webtreees 2.0

**Comment by Fa10175** [comment]
new test
 i delete all table in database
 import database with 1.7.16 data
your module is disable
i connect webtrees lastest version master
i change to put the good directory for my tree ( before ../mydir to /mydir
verify that photos are well display.
remove disable to your module lastest master 
check no changed for me 
sorry to do not help you more for now.
if you find something i am happy to test tomorrow

your files add in module_v4
[webtrees-faces.zip](https://github.com/UksusoFF/webtrees-faces/files/3974620/webtrees-faces.zip)

**Comment by UksusoFF** [comment]
@Fa10175 okay if you can please send me database 1.7.16 dump to email: uksusoff@yandex.ru

**Comment by Fa10175** [comment]
i find something the table ##photo_notes don't exit on database 1.7.16 all data are in table ##module_setting

**Comment by UksusoFF** [comment]
@Fa10175 migration from `module_setting` table added: https://github.com/UksusoFF/webtrees-faces/commit/50aaf0701fa7006a4f4244c530ec6459bda5992f
Please [try it](https://github.com/UksusoFF/webtrees-faces/archive/master.zip).

**Comment by Fa10175** [comment]
I try the latest version
all data from ##module_setting are now in ##media_faces
i saw the photos but when i display it the name is replace buy `undefined` 
The word Zoom  can click his change dark to grey with no effet
they are not area define and name displayed
is not possible to add a new person (no button)
If i check ##media_faces the field f_m_filename after loaded is set to null

**Comment by UksusoFF** [comment]
@Fa10175 
Can you see something on module config page?

**Comment by Fa10175** [comment]
`@UksusoFF`  send by perso mail

**Comment by Fa10175** [comment]
Ok for2.5.2
