### ISSUE TITLE
New media object included at media tab

### ISSUE THREAD

**Issue by alanbenazzi** [UksusoFF/webtrees-faces#21]
After set individual faces on some media, I've noticed that:

- this media had been included on all individuals identified, as a new media object (on Media tab, not only at Faces tab);
- all media objects were reordered to all individuals identified.

I've tested add new object media to a individual (on webtrees default feature) and have not this reorder issue.

**Comment by UksusoFF** [comment]
Please provide some screenshots with describe. I can't understand your problem.

**Comment by alanbenazzi** [comment]
Hi,

Follows what I've performed:
- sent a new media without relate to a individual and created a new media object;
![image](https://user-images.githubusercontent.com/8601622/90990604-2dc65e80-e579-11ea-87b1-ac65d8b5a225.png)

- marked all individuals faces. At this moment, all marked individuals had received a new media object on Media tab, not only at Faces tab. Then it will be used on main photo;
![image](https://user-images.githubusercontent.com/8601622/90991032-6f0c3d80-e57c-11ea-86db-7ed1fd28d439.png)
![image](https://user-images.githubusercontent.com/8601622/90991047-92cf8380-e57c-11ea-887b-54e1bdd07ba4.png)


At this test, I could not reproduce media object reorder. So, please consider only this media inclusion at Media tab as media object.

Kind regards

**Comment by UksusoFF** [comment]
Try to disable linking feature in module settings. Seems you not want new media for individuals.

**Comment by alanbenazzi** [comment]
It worked! Thanks!
