### ISSUE TITLE
Mobile Zoom

### ISSUE THREAD

**Issue by miqrogroove** [UksusoFF/webtrees-faces#25]
When tapping thumbnails in Chrome for Android, the photo viewer layout is not correct unless the page is fully zoomed out before it opens.  This results in semi-random appearance of the photo viewer UI.

The workaround is to pinch the screen before tapping any photos.

Is this a webtrees bug or faces bug?

**Comment by UksusoFF** [comment]
Please post screenshot.

**Comment by miqrogroove** [comment]
![1-before-good](https://user-images.githubusercontent.com/1371835/95687755-9aea8d80-0bd3-11eb-83ab-5b993923486d.jpg)
![2-after-good](https://user-images.githubusercontent.com/1371835/95687756-9b832400-0bd3-11eb-9ff4-80b1a5ea3262.jpg)
![3-before-bad](https://user-images.githubusercontent.com/1371835/95687758-9c1bba80-0bd3-11eb-8eb4-b700abad31ed.jpg)
![4-after-bad](https://user-images.githubusercontent.com/1371835/95687760-9cb45100-0bd3-11eb-877f-c3f58cc44c2e.jpg)

**Comment by UksusoFF** [comment]
Seems it's webtrees issue. Please try to disable Faces and check it with default colorbox.

**Comment by miqrogroove** [comment]
I will close this and test more.  Thank you for checking.
