### ISSUE TITLE
Display "private" for private individuals instead of the XREF

### ISSUE THREAD

**Issue by SodanWT** [UksusoFF/webtrees-faces#3]
Hi,

I'm creating github issues for the glitches listed in my post https://www.webtrees.net/index.php/en/forum/4-customising/33815-webtrees-faces-private-infos-lot-of-names . I think it will be easier for you to track the different bugs this way.

For private individuals, could you display the text "private", not the xref of the individual (see the attached screenshot)? There might be an exiting function doing this as it is a standard behavior of webtrees.

Regards

![Facesv2 5 1](https://user-images.githubusercontent.com/13674759/71359921-69de9500-258e-11ea-872c-9979872215b4.png)

**Comment by UksusoFF** [comment]
I don't have many private people in my tree so can't test it fully.
Please check master version seems it's works.

**Comment by SodanWT** [comment]
Master is ok for me. It works great. Thanks.
