### ISSUE TITLE
/admin/faces-admin/config&mid=X1 gives "You do not have permission to view"

### ISSUE THREAD

**Issue by github-bryld** [UksusoFF/webtrees-faces#30]
Odd new behaviour is happening to my web page:

/admin/faces-admin/config&mid=X1 (and any other media object) now gives me the dreaded:

You do not have permission to view this page.

- even though I am logged in as the administrator

BUT

/admin/faces-admin/config

works fine, so I can still change the faces settings, just not from the settings button at the right side of the chosen image.

The files in the faces module are unaltered, and I can still add face areas fine, when logged in.

I believe it worked in webtrees 2.0.13 but not in 2.0.15 (also tried with a fresh installation)

**Comment by UksusoFF** [comment]
Please try latest master version.

**Comment by github-bryld** [comment]
That seems to work fine, thank you :-)
