### ISSUE TITLE
List of names overlaps the picture

### ISSUE THREAD

**Issue by SodanWT** [UksusoFF/webtrees-faces#4]
Hi,

For pictures with a lot of faces, the list of names largely overlaps the picture (see the attached screenshot). Could the list be under the picture, with a vertical scrollbar when needed?

Regards

![Facesv2 5 1](https://user-images.githubusercontent.com/13674759/71360238-68619c80-258f-11ea-90a5-d721a3e05468.png)

**Comment by UksusoFF** [comment]
When I rewrote the module for webtrees 2.0  could not remember why title was with 12px font-size and remove it.
If make size smaller - it's not so overlaps picture. 
You can do this with [CustomCssJsModule](https://github.com/fisharebest/webtrees/blob/master/app/Module/CustomCssJsModule.php).

But last days I doing insane thing - rewrote  module for change colorbox to other library. 🙈
Can you test latest master and tell me what you think about this?

Now it's look like:
![image](https://user-images.githubusercontent.com/1931442/71424327-fe89e580-26a9-11ea-8caa-486b20d005b3.png)

It's still without working zoom and may contain unexpected bug so this is not release yet.

**Comment by SodanWT** [comment]
Hi, I'm back from holidays :)

That's great! I like it. Both the picture and the names list are always visible. Really nice :)
I also like the new tooltips position.

2 remarks:
- I have a horizontal scrollbar at the bottom of the list, could you make it not appear?
- I have many long names, so they are often ellipsised (which is good), thus we don't have the full information. Could you make the tooltip to show up under the face also when hovering the name is the list?
 
By the way, to make the new version work, I had to take the build https://github.com/UksusoFF/webtrees-faces/commit/7ee8aa956ebaaa859621dbebd1e9b1fb2084d98f, as the build https://github.com/UksusoFF/webtrees-faces/commit/393bc2c7952bbf9bde45340781dea8e88c1779f9 is not working at all: the module does not launch, I have 2 JS errors is the console:
```
TypeError: (intermediate value)(...) is not a function Asset:1:69477 /module/_faces_/Asset?asset=build%2Fvendor.min.js&hash=1577464739
TypeError: e.mapster is undefined Asset:1:20 /module/_faces_/Asset?asset=build%2Fmodule.min.js&hash=1577464739
```

Great work!

**Comment by UksusoFF** [comment]
> I have a horizontal scrollbar at the bottom of the list, could you make it not appear?

Please post screenshot.

> I have many long names, so they are often ellipsised (which is good), thus we don't have the full information. Could you make the tooltip to show up under the face also when hovering the name is the list?

Yep. I will try this.

> I have 2 JS errors is the console

Fixed. Please check master version.

**Comment by SodanWT** [comment]
Master is ok now.

Here is the screenshot with the horizontal scrollbar
![horizontal scrollbar](https://user-images.githubusercontent.com/13674759/71780712-3d7f3b80-2fc6-11ea-92df-dd9c705baf8b.png)

**Comment by UksusoFF** [comment]
> Here is the screenshot with the horizontal scrollbar

Fixed https://github.com/UksusoFF/webtrees-faces/commit/f7d34315753112aba7bab3012631123db8dbc1d1

> Could you make the tooltip to show up under the face also when hovering the name is the list?

Done https://github.com/UksusoFF/webtrees-faces/commit/614a36834228353739cc6d42fde9ed260079b5a2

Please check master version.

**Comment by SodanWT** [comment]
Everything works great, thank you!
