### ISSUE TITLE
The boxes are not displayed if the text contains a comma

### ISSUE THREAD

**Issue by SodanWT** [UksusoFF/webtrees-faces#5]
Hi,

I noticed that the boxes are not displayed if the text contains a comma.
Could this be fixed?

Regards

**Comment by UksusoFF** [comment]
Can you describe your use case? I can't imagine how you want use this. Mark many peoples in one area? Some names can contain comma?

I can fix it by removing comma from key. But this mean that "Hello, world" will be highlighted with "Hello world" too.

**Comment by SodanWT** [comment]
This is when the people does not belong to my tree, so I just add a plain text with no xref. For instance: "This is Ms. X, daughter of Mr. Y"

**Comment by UksusoFF** [comment]
Seems it's fixed.
Please check master version.

**Comment by SodanWT** [comment]
Master is ok. Thanks!
