### ISSUE TITLE
Module causing an error in Webtrees 2.1.0

### ISSUE THREAD

**Issue by clivej** [UksusoFF/webtrees-faces#52]
The module is throwing an error when upgrading site to 2.1.0 of webtrees.  

I have had to rename the /modules_v4/faces folder to faces.disable to be able the use my install.

**Comment by UksusoFF** [comment]
Hi there! Try new version.

**Comment by clivej** [comment]
Uploaded the new version, and all appears to be working fine.  Thanks :)
