### ISSUE TITLE
Problems after upgrading from 2.67 to 2.70

### ISSUE THREAD

**Issue by iyoua** [UksusoFF/webtrees-faces#55]
Before upgrading, people who are not in the genealogy can also mark their names. After upgrading to 2.70, the name identification of non family members cannot be established.

**Comment by zhoueysun** [comment]
I agree. You cannot add the name of a person who is not in the webtrees database, like v.2.6.7 with webtrees 2.0.23. Before you could just type any name if they were not in the database already.

**Comment by UksusoFF** [comment]
Fixed in [v2.7.1](https://github.com/UksusoFF/webtrees-faces/releases/tag/v2.7.1)

**Comment by iyoua** [comment]
Thank you!
