### ISSUE TITLE
Identify a person who is not part of the tree.

### ISSUE THREAD

**Issue by patrickfaivre** [UksusoFF/webtrees-faces#56]
When marking a face, it is proposed: "Give the ID number of the person or another text". With previous versions, I was able to enter a name not belonging to the tree. With version 2.7.0 this is no longer possible. Is this intentional?

**Comment by UksusoFF** [comment]
Fixed in [v2.7.1](https://github.com/UksusoFF/webtrees-faces/releases/tag/v2.7.1)

**Comment by patrickfaivre** [comment]
Thanks, Kirill !
