### ISSUE TITLE
New feature suggestion - 'show all' link, that will display tooltips for all identified people in a picture

### ISSUE THREAD

**Issue by stncrn** [UksusoFF/webtrees-faces#60]
Hello, 

First of all, a big thanks for your work on this module.

I'd like to suggest a new feature :
Adding a _show all_ link/button below the names list, that, on hover, will do the same than each name-link of the list : display the name of all identified people on the image, but this time, all at once.

I tried a naive 
`$('.faces-person-name').trigger('mouseover')`
then tried to iterate manually
`$('.faces-person-name').each(function(){$(this).trigger('mouseover');});`

but I only manage to have a single tooltip at the time (the last of the list).
However, all blue frames are properly drawn.

![image](https://user-images.githubusercontent.com/25079376/188332713-bbd17557-3357-4533-909c-51659bfb8449.png)

I'm having trouble in identifying why only one tooltip stays active at the time, an how to change this behaviour.

I know that, on a picture like this one, several tooltips will be overlapping.
A solution may be to have instead a _highlight all known faces_ switch, that will activate/deactivate all the blue frames, then the user may perform a regular mouseover on names or faces to show the tooltips. On mouseout, the blue frames will stay there, until the _highlight all known faces_ is disabled.

**Comment by UksusoFF** [comment]
@stncrn 
Check latest master version
![image](https://user-images.githubusercontent.com/1931442/233635095-99e05fed-6f61-4872-88a4-e8940d17cc1c.png)

**Comment by HerzScheisse** [comment]
hi, i guees this issue can be closed as solved?!
