### ISSUE TITLE
Fact::getMedia() has been removed

### ISSUE THREAD

**Issue by fisharebest** [UksusoFF/webtrees-faces#63]
Hi UkSusoFF.

Your module uses the function `Fact::getMedia()`.

It was removed in the core code because it was not used.

If you need this logic, you should now copy the function to your own code.

Apologies.  If I knew that you were using this function, I would have discussed it with you  beforehand.

See https://www.webtrees.net/index.php/en/forum/4-customising/37075-webtrees-faces-display-undefined

**Comment by UksusoFF** [comment]
Fixed in https://github.com/UksusoFF/webtrees-faces/releases/tag/v2.7.2
