### ISSUE TITLE
Title not displayed

### ISSUE THREAD

**Issue by Fa10175** [UksusoFF/webtrees-faces#7]
![Sans titre](https://user-images.githubusercontent.com/10681601/71483608-f72d1e00-2808-11ea-92cf-a222272a1a08.jpg)

**Comment by UksusoFF** [comment]
Master version still on development :)
Now rewriting tooltips position.

**Comment by UksusoFF** [comment]
Please check master version.

**Comment by Fa10175** [comment]
i just check the lastest master version and i very good for me.
i prefer this version 
Thanks
