### ISSUE TITLE
Face Taging 

### ISSUE THREAD

**Issue by MYLE-01** [UksusoFF/webtrees-faces#77]
Love it Using it Heaps THANKS

found a way to display their age 

if i create a custom GEDCOM

edit Edit the raw GEDCOM

```
1 EVEN
2 TYPE Family Reunion
2 DATE 2013
2 OBJE @X287@
```
it create this

![image](https://user-images.githubusercontent.com/4362345/226764948-72cc0a7d-35a1-4a43-b232-9f0cda9c7f59.png)

that @X287@ is a photo i have face tag

If click and go into that object

![image](https://user-images.githubusercontent.com/4362345/226765146-0b84fcac-748a-45e3-9992-21cb3ff44112.png)

it has added my custom GEDCOM data to it.

how would stop display all those 2013

**Comment by MYLE-01** [comment]
BEEN thinking 

What about this for an idea

Dont know how to code in PHP

adding

![image](https://user-images.githubusercontent.com/4362345/226771594-d18f2f99-cbed-43c4-ac8c-1db4eb50dda4.png)

to

![image](https://user-images.githubusercontent.com/4362345/226771465-ab5b66fe-30ee-4c4a-8ad3-74b3b5f0240e.png)

with the trick option to add to  Facts and events  TAB
which would display like this in   Facts and events TAB

![image](https://user-images.githubusercontent.com/4362345/226772655-41c799bc-c691-43d7-8cc8-56fd2e091c5b.png)


it saves the current values of Event: Type of Event: Date of Event: for the next person been tagged

the GEDCOM data would look like 

```
1 EVEN Family Reunion
2 TYPE Face Tagged
2 DATE 2013
2 OBJE @X287@
```

**Comment by UksusoFF** [comment]
Please reproduce year duplication in demo tree: 
https://tree.iamdrunk.ru/tree/jfk
Login: demo
Password: demodemo

**Comment by MYLE-01** [comment]
sorry about long delay

but here

add a fact

![image](https://user-images.githubusercontent.com/4362345/231279329-260690e1-c6bf-4d95-9825-6c5282650bc9.png)



now if you go into that Images

![image](https://user-images.githubusercontent.com/4362345/231279670-9170bfca-d18a-435e-9fd2-43fc74411d02.png)

its how the fact is stored

```
1 EVEN Civil rights leaders meet with President John F. Kennedy
2 TYPE FACT
2 DATE 23 AUG 1963    #<<< think this is the problem
2 OBJE @X60X@  
```
with the 
```
2 DATE 1963
```
you get 

![image](https://user-images.githubusercontent.com/4362345/231283299-73b9919f-be92-4c33-8506-fb90daf04558.png)

if you paste that GEDCOM into another person who is face tag in same photo you see it duperating

see I copy/paste to other person

![image](https://user-images.githubusercontent.com/4362345/231312814-0d45b0fe-0be5-473a-a220-9db4e4f61e5c.png)

the 1963 one  is  in Peter Sydney Lawford fact/event 




like the  new paste option at bottom for the fact and events  is that in the next update

**Comment by UksusoFF** [comment]
@MYLE-01 dates duplication fixed in master version.

But still can't understand in which cases you need various date format `23 AUG 1963` and `1963`. Seems you can adjust it in all facts?

**Comment by MYLE-01** [comment]
only did the 2 different dates to help you find see the problem I was having

Thanks Bro for the update
