### ISSUE TITLE
Better display of the names list

### ISSUE THREAD

**Issue by SodanWT** [UksusoFF/webtrees-faces#8]
Hi Kirill,

Two more improvements to your module:

1) Could you make 1 name per line in the list? When there are short names, they will be easier to notice. The comma at the end of each name could then be removed.
Actual:
![list2](https://user-images.githubusercontent.com/13674759/71855895-9b08aa80-30e2-11ea-8563-b15901ad9018.png)
Proposition:
![list2-mod](https://user-images.githubusercontent.com/13674759/71855451-5b8d8e80-30e1-11ea-869c-2471c5a14e73.png)

2) Could you give a little more space to the names list so with admin rights the link to detach a name is not hidden by the vertical scrollbar. I think 10px will be enough.
Actual:
![List3](https://user-images.githubusercontent.com/13674759/71855612-cfc83200-30e1-11ea-9f29-3e1d69a85cdd.png)
Proposition:
![List3-mod](https://user-images.githubusercontent.com/13674759/71855610-cf2f9b80-30e1-11ea-9098-3757870b5729.png)

Regards

**Comment by UksusoFF** [comment]
> Could you give a little more space to the names list so with admin rights the link to detach a name is not hidden by the vertical scrollbar.

Which OS and browser you use? I can't reproduce this.

**Comment by SodanWT** [comment]
I'm using Firefox 71 on Ubuntu 19.10

**Comment by UksusoFF** [comment]
@SodanWT 
Please check master version.

**Comment by SodanWT** [comment]
Everything is ok, thanks!
