### ISSUE TITLE
Photo color temp +

### ISSUE THREAD

**Issue by Anj2E** [UksusoFF/webtrees-faces#86]
Thank you for the wonderful module!

I noticed, however, when comparing the rendering of images while using the faces module vs not using the faces module (side-by-side comparison on same monitor), that the image color temperature is cooler with the faces module, causing some colors to not render true.  There also appears to be somewhat less contrast in the images when viewed using the faces module, making them appear softer / less sharp.

Why is this occurring and is there a way to keep the same color temp and contrast as the stock webtrees image renderer?

Thanks in advance!

**Comment by UksusoFF** [comment]
Can you show video with compare this?
Maybe it's because we use different image viewer.

**Comment by Anj2E** [comment]
Thank you so much for your prompt response.
 
After reviewing this further, I feel I am mistaken.  I believe it was the lighting combined with the fact that the photos are larger using the faces module.
 
Please feel free to delete my original question entirely as it may cause confusion to others.
 
Looking forward to using your wonderful module!
 
Thanks again,
Anjali
