### ISSUE TITLE
Call to undefined function

### ISSUE THREAD

**Issue by gatonero** [UksusoFF/webtrees-faces#88]
I'm running the latest version of webtrees 2.0. The faces module stops webtrees from running. 

[webtrees-faces.log](https://github.com/user-attachments/files/17966543/webtrees-faces.log)

**Comment by UksusoFF** [comment]
Please updete webtrees or use old version of module: https://github.com/UksusoFF/webtrees-faces?tab=readme-ov-file#old-version

**Comment by gatonero** [comment]
I'm running image: ghcr.io/nathanvaughn/webtrees:latest (app) and image: docker.io/library/mariadb:11

**Comment by UksusoFF** [comment]
Show screenshot of your webtrees version from admin panel.

**Comment by gatonero** [comment]
I can't show you the panel because webtrees crashes.  Just yesterday I pulled image: ghcr.io/nathanvaughn/webtrees:latest.

**Comment by UksusoFF** [comment]
Remove module, check webtrees works, take screenshot, install module

**Comment by gatonero** [comment]
I just installed image: nathanvaughn/webtrees:2.1.20 and that works.

**Comment by gatonero** [comment]
The troubles start with nathanvaughn/webtrees:2.2.0

**Comment by gatonero** [comment]
nathanvaughn/webtrees:2.1.21 is the last working version.

**Comment by UksusoFF** [comment]
https://github.com/UksusoFF/webtrees-faces/releases/tag/v2.7.3
