### ISSUE TITLE
Upgrade webtrees-faces for webtrees version 2.2

### ISSUE THREAD

**Issue by gudjonsi** [UksusoFF/webtrees-faces#89]
Upgrade to webtrees-faces to make it compatible with webtrees version 2.2 would be very much appreciated. Best regards.

**Comment by gudjonsi** [comment]
After installing newly released webtrees-faces v2.7.2 to webtrees version 2.2.1 it causes errors, see enclosed text file. (Server PHP version 8.3.9). Best regards.
[webtrees-faces-v272-Errors.txt](https://github.com/user-attachments/files/17989929/webtrees-faces-v272-Errors.txt)

**Comment by UksusoFF** [comment]
https://github.com/UksusoFF/webtrees-faces/releases/tag/v2.7.3

**Comment by gudjonsi** [comment]
Thanks, issue solved. Best regards.
