### ISSUE TITLE
Add language translation

### ISSUE THREAD

**Issue by DaPoHou** [UksusoFF/webtrees-faces#9]
Add a language translation file so I can translate it into different languages? Thank you!

**Comment by UksusoFF** [comment]
Are you really need translation? :) In module very few string with texts. Most of all "Cancel", "Add" etc

**Comment by DaPoHou** [comment]
Yes.
We should take into all users, especially the elderly who do not speak English.

**Comment by UksusoFF** [comment]
@xmlf welcome: https://github.com/UksusoFF/webtrees-faces/tree/master/resources/langs :)

**Comment by UksusoFF** [comment]
Thanks to @AndreasRauhut for DE/FR translations.
